---
changelog:
  exclude:
    labels:
      - ignore-for-release
      - tagpr

  categories:
    - title: Features 🎉
      labels: ["enhancement"]
    - title: Bug Fixes 🐌
      labels: ["bug"]
    - title: Documentation 🗒️
      labels: ["documentation"]
    - title: Dependency Updates 📦
      labels:
        - "manager:cargo"
    - title: Development Environment 🔧
      labels:
        - "manager:mise"
        - "manager:github-actions"
        - "manager:dockerfile"
        - "manager:regex"
        - "depType:action"
        - "renovate"
    - title: Other Changes
      labels: ["*"]
