[package]
name = "brust"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = "symbols"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
reqwest = { version = "0.12.23", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.137"

[dev-dependencies]
assert_cmd = "=2.0.17"
