[package]
name = "brust"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = "symbols"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }

[dev-dependencies]
assert_cmd = "=2.0.17"
