# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: "Setup Rust"
description: "Setup rust"
inputs:
  just:
    description: "just version"
    required: true
    default: ""
  sccache:
    description: "sccache version"
    required: true
    default: ""
  sccache_disable_annotations:
    description: "sccache disable_annotations"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      with:
        disable_annotations: ${{ inputs.sccache_disable_annotations == 'true' }}
        version: ${{ inputs.sccache }}

    - name: Cache rustup
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.rustup/settings.toml
          ~/.rustup/toolchains/1.*
        key: v0-rust-rustup-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/rust-toolchain.toml') }}

    - uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1
      with:
        cache-shared-key: cargo-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Install just
      uses: taiki-e/install-action@6f69ec9970ed0c500b1b76d648e05c4c7e0e5671 # v2
      with:
        tool: just@${{ inputs.just }}
