name: "Release Action"
description: "Common release workflow for building and publishing releases"
inputs:
  tag:
    description: "Tag to release"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build release binary
      shell: bash
      run: |
        cargo build --release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: inputs.tag != ''
      with:
        tag_name: ${{ inputs.tag }}
        files: |
          target/release/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
