name: Rust Security audit

on:
  schedule:
    - cron: "0 0 */3 * *"

  push:
    paths: &on_paths
      - "**/Cargo.toml"
      - "**/Cargo.lock"

  pull_request:
    paths: *on_paths

  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5

      - name: Install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit

      - name: Run audit
        run: cargo audit
