# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Rust Security audit

on:
  schedule:
    - cron: "0 0 */3 * *"

  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read # Required to checkout the repository

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install cargo-audit
        uses: taiki-e/install-action@c5b1b6f479c32f356cc6f4ba672a47f63853b13b # v2.62.38
        with:
          tool: cargo-audit

      - name: Run audit
        run: cargo audit
