# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Rust Security audit

on:
  schedule:
    - cron: "0 0 */3 * *"

  push:
    paths: &on_paths
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    paths: *on_paths

  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install cargo-audit
        uses: taiki-e/install-action@056c0cf25f54702ec6dde8b9c8a0387b857627ab # v2
        with:
          tool: cargo-audit

      - name: Run audit
        run: cargo audit
