name: Rust CI

on:
  push:
    branches: ["main"]
    # paths:
    #   - "**src/**.rs"
    #   - "**.rs"
    #   - "Cargo.lock"
    #   - "Cargo.toml"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: rui314/setup-mold@v1
        with:
          mold-version: 2.40.4
          make-default: false

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: "v0.10.0"

      - name: Build
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose
