name: Rust CI

on:
  push:
    branches: ["main"]
    # paths:
    #   - "**src/**.rs"
    #   - "**.rs"
    #   - "Cargo.lock"
    #   - "Cargo.toml"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5

      - name: Check version consistency
        id: versions
        run: |
          set -euxo pipefail
          echo "Checking Rust version consistency between Dockerfile and CI..."
          rust_version=$(grep -E '^FROM rust:[0-9]+\.[0-9]+' Dockerfile | sed -E 's/FROM rust:([0-9]+\.[0-9]+).*/\1/')
          echo "Dockerfile Rust version: $rust_version"
          echo "rust=${rust_version}" >> "$GITHUB_OUTPUT"
          echo "✅ Rust versions are consistent!"

          echo "Checking sccache version consistency between Dockerfile and CI..."
          sccache_version=$(grep -E '^ARG SCCACHE_VERSION=v[0-9]+\.[0-9]+\.[0-9]+' Dockerfile | sed -E 's/ARG SCCACHE_VERSION=(v[0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "Dockerfile sccache version: $sccache_version"
          echo "sccache=${sccache_version}" >> "$GITHUB_OUTPUT"
          echo "✅ sccache versions are consistent!"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: ${{ steps.versions.outputs.sccache }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ steps.versions.outputs.rust }}
          components: rustfmt, clippy

      - name: Install dprint
        run: |
          set -euxo pipefail
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "$HOME/.dprint/bin" >> $GITHUB_PATH

      - name: Check dprint formatting
        run: |
          set -euxo pipefail
          dprint check

      - name: Check cargo formatting
        run: |
          set -euxo pipefail
          cargo fmt -- --check

      - name: Run clippy
        run: |
          set -euxo pipefail
          cargo clippy --all-targets --all-features -- -D warnings

  check:
    runs-on: ubuntu-latest
    needs: fmt
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: ${{ steps.versions.outputs.sccache }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ steps.versions.outputs.rust }}
          target: ${{ matrix.target }}

      - name: Check compilation
        run: |
          set -euxo pipefail
          cargo check --target ${{ matrix.target }} --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    needs: [fmt, check]
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: ${{ steps.versions.outputs.sccache }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ steps.versions.outputs.rust }}

      - name: Install cargo-binstall
        run: |
          set -euxo pipefail
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-llvm-cov
        run: |
          set -euxo pipefail
          cargo binstall cargo-llvm-cov --no-confirm --verbose

      - name: Run tests
        run: |
          set -euxo pipefail
          cargo test --release

      - name: Generate coverage report
        run: |
          set -euxo pipefail
          cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: lcov.info

  build:
    runs-on: ubuntu-latest
    needs: [fmt, check, test]
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: ${{ steps.versions.outputs.sccache }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ steps.versions.outputs.rust }}
          target: ${{ matrix.target }}

      - name: Install cargo-binstall
        run: |
          set -euxo pipefail
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cross
        run: |
          set -euxo pipefail
          cargo binstall cross --no-confirm

      - name: Build release binary
        run: |
          set -euxo pipefail
          cross build --release --target ${{ matrix.target }}

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/brust${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
