name: Rust CI

on:
  push:
    branches: [main]
    paths: &on_paths
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/ci.yaml"
      - "rust-toolchain.toml"

  pull_request:
    paths: *on_paths
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      binary_name: ${{ steps.versions.outputs.binary_name }}
      dprint: ${{ steps.versions.outputs.dprint }}
      just: ${{ steps.versions.outputs.just }}
      package_name: ${{ steps.versions.outputs.package_name }}
      sccache: ${{ steps.versions.outputs.sccache }}

    steps:
      - uses: actions/checkout@v5

      - name: Check version consistency
        id: versions
        run: |
          set -euxo pipefail
          echo "Checking Rust version consistency between Dockerfile and CI..."
          rust_version=$(grep -E '^FROM rust:[0-9]+\.[0-9]+\.[0-9]+' Dockerfile | sed -E 's/FROM rust:([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          tool_version=$(grep -E '^channel = "[0-9]+\.[0-9]+\.[0-9]+"' rust-toolchain.toml | sed -E 's/channel = "([0-9]+\.[0-9]+\.[0-9]+)"/\1/')
          if [ "$rust_version" != "$tool_version" ]; then
            echo "ERROR: Rust version mismatch!"
            echo "Dockerfile         : $rust_version"
            echo "rust-toolchain.toml: $tool_version"
            echo "Please update rust-toolchain.toml in ci.yaml or Dockerfile to match."
            exit 1
          fi
          echo "✅ Rust versions are consistent!"

          echo "Checking sccache version consistency between Dockerfile and CI..."
          sccache_version=$(grep -E '^ARG SCCACHE_VERSION=v[0-9]+\.[0-9]+\.[0-9]+' Dockerfile | sed -E 's/ARG SCCACHE_VERSION=(v[0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "Dockerfile sccache version: $sccache_version"
          echo "sccache=${sccache_version}" >> "$GITHUB_OUTPUT"
          echo "✅ sccache versions are consistent!"

          echo "Checking dprint version consistency between Dockerfile and CI..."
          dprint_version=$(grep -E '^ARG DPRINT_VERSION=[0-9]+\.[0-9]+\.[0-9]+' Dockerfile | sed -E 's/ARG DPRINT_VERSION=([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "Dockerfile dprint version: $dprint_version"
          echo "dprint=${dprint_version}" >> "$GITHUB_OUTPUT"
          echo "✅ dprint versions are consistent!"

          echo "Checking just version consistency between Dockerfile and CI..."
          just_version=$(grep -E '^ARG JUST_VERSION=[0-9]+\.[0-9]+\.[0-9]+' Dockerfile | sed -E 's/ARG JUST_VERSION=([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "Dockerfile just version: $just_version"
          echo "just=${just_version}" >> "$GITHUB_OUTPUT"
          echo "✅ just versions are consistent!"

          echo "Extracting binary name from Cargo.toml..."
          # First get the package name
          package_name=$(grep -E '^\[package\]' -A 10 Cargo.toml | grep -E '^name = "' | sed -E 's/name = "(.*)"/\1/')

          # Check if there are [[bin]] sections
          if grep -q '^\[\[bin\]\]' Cargo.toml; then
            # Look for a bin with the same name as package (main binary)
            main_bin=$(grep -E '^\[\[bin\]\]' -A 10 Cargo.toml | grep -E '^name = "'"$package_name"'"' | sed -E 's/name = "(.*)"/\1/')
            if [ -n "$main_bin" ]; then
              binary_name="$main_bin"
            else
              # Use the first bin found
              binary_name=$(grep -E '^\[\[bin\]\]' -A 10 Cargo.toml | grep -E '^name = "' | head -n 1 | sed -E 's/name = "(.*)"/\1/')
            fi
          else
            # No [[bin]] sections, use package name
            binary_name="$package_name"
          fi

          echo "Binary name: $binary_name"
          echo "binary_name=${binary_name}" >> "$GITHUB_OUTPUT"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          disable_annotations: true
          version: ${{ steps.versions.outputs.sccache }}

      - name: Cache rustup
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/1.*
          key: v0-rust-rustup-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/rust-toolchain.toml') }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          cache-shared-key: cargo-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dprint
        uses: taiki-e/install-action@v2
        with:
          tool: dprint@${{ steps.versions.outputs.dprint }}

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just@${{ steps.versions.outputs.just }}

      - name: Check dprint formatting
        run: |
          set -euxo pipefail
          just dprint

      - name: Check cargo formatting
        run: |
          set -euxo pipefail
          just cargo-fmt

      - name: Run clippy
        run: |
          set -euxo pipefail
          just cargo-clippy

  check:
    name: check
    runs-on: ubuntu-latest
    needs: fmt
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          disable_annotations: true
          version: ${{ needs.fmt.outputs.sccache }}

      - name: Cache rustup
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/1.*
          key: v0-rust-rustup-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/rust-toolchain.toml') }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: cargo-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Check compilation
        run: |
          set -euxo pipefail
          just cargo-check

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [fmt, check]
    timeout-minutes: 15
    permissions:
      actions: read #         For octocov to retrieve previous reports from artifacts
      contents: write #       For octocov to push badges to repository
      pull-requests: write #  For octocov to comment on pull requests

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: ${{ needs.fmt.outputs.sccache }}

      - name: Cache rustup
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/1.*
          key: v0-rust-rustup-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/rust-toolchain.toml') }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: cargo-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-binstall
        run: |
          set -euxo pipefail
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-llvm-cov
        run: |
          set -euxo pipefail
          cargo binstall cargo-llvm-cov --no-confirm --force

      - name: Generate coverage report
        run: |
          set -euxo pipefail
          just cargo-llvm-cov

      - name: Upload coverage
        uses: k1LoW/octocov-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [fmt, check, test]
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: ${{ needs.fmt.outputs.sccache }}

      - name: Cache rustup
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/1.*
          key: v0-rust-rustup-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/rust-toolchain.toml') }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: cargo-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: |
          set -euxo pipefail
          just cargo-build release

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ needs.fmt.outputs.binary_name }}
          path: target/release/${{ needs.fmt.outputs.binary_name }}
