# Cleanup caches by a branch
# Cleanup container

name: Cleanup

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  cleanup:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
    steps:
      - name: Convert repository name to lowercase
        id: repo_name
        run: |
          echo "lowercase=${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Cleanup Cache
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R "${REPO}" -B "${BRANCH}" | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              echo "Deleting cacheKey... ${cacheKey}"
              gh actions-cache delete "${cacheKey}" -R "${REPO}" -B "${BRANCH}" --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          # BRANCH: ${{ github.ref }}
          # https://github.com/github/docs/issues/22727
          # BRANCH: 'refs/pull/${{ github.event.pull_request.number }}/merge'
          # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-based-on-the-head-or-base-branch-of-a-pull-request
          BRANCH: ${{ github.head_ref || github.ref_name }}

      - name: Delete untagged containers
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ steps.repo_name.outputs.lowercase }}/devcontainer
          package-type: "container"
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
